---
apiVersion: batch/v1
kind: Job
metadata:
  name: grid-job
spec:
  ttlSecondsAfterFinished: 172800
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: job-container
          image: git.computecanada.ca:4567/rptaylor/misc/atlas-grid-centos7-localuser:20220809
          volumeMounts:
            - name: cvmfs-atlas
              mountPath: /cvmfs/atlas.cern.ch/repo
              readOnly: true
            - name: cvmfs-atlas-condb
              mountPath: /cvmfs/atlas-condb.cern.ch/repo
              readOnly: true
            - name: cvmfs-atlas-nightlies
              mountPath: /cvmfs/atlas-nightlies.cern.ch/repo
              readOnly: true
            - name: cvmfs-sft
              mountPath: /cvmfs/sft.cern.ch
              readOnly: true
            - name: cvmfs-sft-nightlies
              mountPath: /cvmfs/sft-nightlies.cern.ch
              readOnly: true
            - name: cvmfs-unpacked
              mountPath: /cvmfs/unpacked.cern.ch
              readOnly: true
            - name: secret-volume
              mountPath: /proxy
              readOnly: true
            - name: pilot-dir
              mountPath: /pilotdir
          env:
            - name: PILOT_NOKILL
              value: "True"
          # command: ["/usr/bin/bash"]
          # args: ["-c", "cd; wget https://pandaserver.cern.ch:25443/cache/k8s/pilots_starter --no-check-certificate; chmod 755 pilots_starter; ./pilots_starter"]
      volumes:
        - name: cvmfs-atlas
          hostPath:
            path: /cvmfs/atlas.cern.ch/repo
            type: Directory
        - name: cvmfs-atlas-condb
          hostPath:
            path: /cvmfs/atlas-condb.cern.ch/repo
            type: Directory
        - name: cvmfs-atlas-nightlies
          hostPath:
            path: /cvmfs/atlas-nightlies.cern.ch/repo
            type: Directory
        - name: cvmfs-sft
          hostPath:
            path: /cvmfs/sft.cern.ch
            type: Directory
        - name: cvmfs-sft-nightlies
          hostPath:
            path: /cvmfs/sft-nightlies.cern.ch
            type: Directory
        - name: cvmfs-unpacked
          hostPath:
            path: /cvmfs/unpacked.cern.ch
            type: Directory
        - name: secret-volume
          secret:
            secretName: proxy-secret
            defaultMode: 0400
        - name: pilot-dir
          emptyDir: {}
