---
apiVersion: batch/v1
kind: Job
metadata:
  name: grid-job
spec:
  ttlSecondsAfterFinished: 172800
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      securityContext:
        fsGroup: 1000
      serviceAccountName: harvester-service-account
      containers:
        - name: atlas-grid-alma9
          image: gitlab-registry.cern.ch/panda/harvester-k8s-images/adc-alma9:latest
          securityContext:
             allowPrivilegeEscalation: true
             privileged: true
          env:
            - name: PILOT_NOKILL
              value: "True"
          volumeMounts:
            - name: cvmfs
              mountPath: /cvmfs
              readOnly: true
              mountPropagation: HostToContainer
            - name: proxy-secret
              mountPath: /proxy
            - name: pilot-dir
              mountPath: /pilotdir
          livenessProbe:
            exec:
              command:  # returns 0 if log changed less than 10 min ago, otherwise 1
              - /bin/sh
              - -c
              - find /tmp/wrapper-wid.log -mmin -10 | egrep '.*'
            initialDelaySeconds: 300
            periodSeconds: 300
            failureThreshold: 3
      volumes:
        - name: cvmfs
          hostPath:
            path: /opt/cvmfs
            type: Directory
        - name: proxy-secret
          secret:
            secretName: proxy-secret
            defaultMode: 0400
        - name: pilot-dir
          emptyDir: {}

