---
apiVersion: batch/v1
kind: Job
metadata:
  name: grid-job
spec:
  ttlSecondsAfterFinished: 172800
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      securityContext:
        fsGroup: 1000
      containers:
        - name: atlas-grid-alma9
          resources:
            limits:
              nvidia.com/gpu: 1
          image: gitlab-registry.cern.ch/panda/harvester-k8s-images/adc-alma9:latest
          securityContext:
             allowPrivilegeEscalation: true
             privileged: true
          env:
            - name: PILOT_NOKILL
              value: "True"
            - name: SINGULARITYENV_LD_LIBRARY_PATH
              value: /usr/local/nvidia/lib64
            - name: SINGULARITYENV_PREPEND_PATH
              value: /usr/local/nvidia/bin
            # - name: ALRB_rucioVersion
            #  value: "1.25.5.post1"
          volumeMounts:
            - name: cvmfs
              mountPath: /cvmfs
              readOnly: true
              mountPropagation: HostToContainer
            - name: proxy-secret
              mountPath: /proxy
            - name: pilot-dir
              mountPath: /pilotdir
          livenessProbe:
            exec:
              command:  # returns 0 if log changed less than 10 min ago, otherwise 1
              - /bin/sh
              - -c
              - "[ `df -h | grep cvmfs2 | wc -l` -eq 7 ] && find ${TMPDIR:-/tmp}/wrapper-wid.log -mmin -10 | egrep '.*'"
            initialDelaySeconds: 60
            periodSeconds: 120
            failureThreshold: 3
      volumes:
        - name: cvmfs
          hostPath:
            path: /var/lib/cvmfs-k8s
            type: Directory
        - name: proxy-secret
          secret:
            secretName: proxy-secret
            defaultMode: 0400
        - name: pilot-dir
          emptyDir: {}
