---
apiVersion: batch/v1
kind: Job
metadata:
  name: grid-job
spec:
  ttlSecondsAfterFinished: 172800
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      securityContext:
        fsGroup: 1000
      containers:
        - name: atlas-grid-alma9
          securityContext:
             allowPrivilegeEscalation: true
             privileged: true
             # runAsUser: 2001
          image: gitlab-registry.cern.ch/panda/harvester-k8s-images/adc-alma9:latest
          env:
            - name: PILOT_NOKILL
              value: "True"
          command: [ "/usr/bin/bash" ]
          args: [ "-c", "cd; python $EXEC_DIR/pilots_starter.py" ]
          volumeMounts:
            - name: atlas
              mountPath: /cvmfs/atlas.cern.ch
              readOnly: true
            - name: atlas-condb
              mountPath: /cvmfs/atlas-condb.cern.ch
              readOnly: true
            - name: atlas-nightlies
              mountPath: /cvmfs/atlas-nightlies.cern.ch
              readOnly: true
            - name: sft
              mountPath: /cvmfs/sft.cern.ch
              readOnly: true
            - name: sft-nightlies
              mountPath: /cvmfs/sft-nightlies.cern.ch
              readOnly: true
            - name: grid
              mountPath: /cvmfs/grid.cern.ch
              readOnly: true
            - name: unpacked
              mountPath: /cvmfs/unpacked.cern.ch
              readOnly: true
            - name: proxy-secret
              mountPath: /proxy
              readOnly: true
            - name: pilot-dir
              mountPath: /pilotdir
          livenessProbe:
            exec:
              command:  # returns 0 if log changed less than 10 min ago, otherwise 1
              - /bin/sh
              - -c
              - find /tmp/wrapper-wid.log -mmin -10 | egrep '.*'
            initialDelaySeconds: 300
            periodSeconds: 300
            failureThreshold: 3
      volumes:
        - name: atlas
          hostPath:
            path: /cvmfs/atlas.cern.ch
            type: Directory
        - name: atlas-condb
          hostPath:
            path: /cvmfs/atlas-condb.cern.ch
            type: Directory
        - name: atlas-nightlies
          hostPath:
            path: /cvmfs/atlas-nightlies.cern.ch
            type: Directory
        - name: sft
          hostPath:
            path: /cvmfs/sft.cern.ch
            type: Directory
        - name: sft-nightlies
          hostPath:
            path: /cvmfs/sft-nightlies.cern.ch
            type: Directory
        - name: grid
          hostPath:
            path: /cvmfs/grid.cern.ch
            type: Directory
        - name: unpacked
          hostPath:
            path: /cvmfs/unpacked.cern.ch
            type: Directory
        - name: proxy-secret
          secret:
              secretName: proxy-secret
              defaultMode: 0400
        - name: pilot-dir
          emptyDir: {}
