---
apiVersion: batch/v1
kind: Job
metadata:
  name: grid-job
spec:
  ttlSecondsAfterFinished: 172800
  backoffLimit: 0
  template:
    metadata:
       annotations:
          cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
    spec:
      tolerations:
      - key: "arm-processor"
        operator: "Exists"
        effect: "NoSchedule"
      nodeSelector:
        kubernetes.io/arch: arm64
      restartPolicy: Never
      containers:
        - name: atlas-grid-centos9s
          image: fbarreir/adc-centos9s-singularity:latest
          securityContext:
             allowPrivilegeEscalation: true
             privileged: true
          env:
            - name: PILOT_NOKILL
              value: "True"
            # - name: ALRB_rucioVersion
            #  value: "1.25.5.post1"
          command: ["/usr/bin/bash"]
          args: ["-c", "cd; python3 $EXEC_DIR/pilots_starter.py"]
          volumeMounts:
            - name: cvmfs
              mountPath: /cvmfs
              readOnly: true
              mountPropagation: HostToContainer
            - name: proxy-secret
              mountPath: /proxy
            - name: pilot-dir
              mountPath: /pilotdir
          livenessProbe:
            exec:
              command:  # returns 0 if log changed less than 10 min ago, otherwise 1
              - /bin/sh
              - -c
              - find /tmp/wrapper-wid.log -mmin -10 | egrep '.*'
            initialDelaySeconds: 300
            periodSeconds: 300
            failureThreshold: 3
      volumes:
        - name: cvmfs
          hostPath:
            path: /var/lib/cvmfs-k8s
            type: Directory
        - name: proxy-secret
          secret:
              secretName: proxy-secret
        - name: pilot-dir
          emptyDir: {}
